version: "3"


services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
    volumes:
      - /data:/data
    command: server /data
    networks:
      data_plataform_network:
        ipv4_address: 172.26.0.3 

  init_minio:
    build: ./minio
    depends_on:
      - minio 
    networks:
      data_plataform_network:

  kafka-man:
    build: ./kafka-man
    depends_on:
      - init_minio
    networks:
      data_plataform_network:

  jedi:
    depends_on:
      - init_minio
    build: ./jedi
    networks:
      data_plataform_network:

  sync_minio_airflow:
    depends_on:
      - minio
    build: ./sync_minio_airflow
    networks:
      data_plataform_network:
    volumes:
      - "/home/gustavo/Desktop/Luizalabs/curso/portifolio/data_plataform/airflow/dags:/app/dags"

networks:
  data_plataform_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/24 
